apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf-classification-gpu
  labels:
    app: hf-runner
    backend: gpu
spec:
  selector:
    matchLabels:
      app: hf-runner
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hf-runner
        backend: gpu
      annotations:
        backend: GPU
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - gpu-rtx3090
      containers:
        - name: hf-serve
          image: sharockys/hfserve
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: hf-http
          resources:
            requests:
              memory: 8G
              cpu: "2"
            limits:
              memory: 14G
              nvidia.com/gpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: hf-classification-gpu-service
spec:
  selector:
    app: hf-runner
  ports:
    - name: hf-inference-service-port
      protocol: TCP
      port: 80
      targetPort: hf-http
  type: LoadBalancer
