apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf-classification-cpu
  labels:
    app: hf-runner
    backend: cpu
spec:
  selector:
    matchLabels:
      app: hf-runner
  replicas: 6
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hf-runner
        backend: cpu
      annotations:
        backend: CPU
    spec:
      containers:
        - name: hf-serve
          image: sharockys/hfserve
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: hf-http
          resources:
            requests:
              memory: 8G
              cpu: "4"
            limits:
              memory: 14G
          env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: none
               
---
apiVersion: v1
kind: Service
metadata:
  name: hf-classification-cpu-service
spec:
  selector:
    app: hf-runner
  ports:
    - name: hf-inference-service-port
      protocol: TCP
      port: 80
      targetPort: hf-http
  type: LoadBalancer
